### PR TITLE
PR for issue/73

### LINKED ISSUE #73: Exception handling and constraint error state
### Description

If a constraint cannot be checked, because there is an exception (e.g. column not existing), it should not crash the program but just let the constraint enter an error state.
### Open Points
- [x] `[warn] /Users/frosner/Documents/projects/drunken-data-quality/src/main/scala/de/frosner/ddq/constraints/NeverNullConstraintResult.scala:11: match may not be exhaustive.`  
  `[warn] It would fail on the following inputs: (??, None, None, Some(_)), (??, Option(), None, Some(_)), (ConstraintError(_), None, None, Some(_)), (ConstraintError(_), None, Some(_), None), (ConstraintError(_), None, Some(_), Some(_)), (ConstraintError(_), Option(), None, Some(_)), (ConstraintError(_), Option(), Option(), Some(_)), (ConstraintError(_), Option(), Some(_), None), (ConstraintError(_), Some(_), None, Some(_)), (ConstraintError(_), Some(_), Some(_), None), (ConstraintFailure, None, None, None), (ConstraintFailure, None, None, Some(_)), (ConstraintFailure, Option(), None, None), (ConstraintFailure, Option(), None, Some(_)), (ConstraintSuccess, None, None, Some(_)), (ConstraintSuccess, None, Some(_), Some(_))`
- [x] Maybe restructure classes and tests? One file per constraint + result + data and then one test for this? Or keep the ConstraintTest, ConstraintResultTest?
- [x] Maybe it is better to put everything in one Try inside the constraints to avoid .gets on things that might not exist when people change the flow.
- [x] Create a set of manual tests for each constraint we have + each reporter combination to use it for manual testing the outputs etc. => @Bantolomeus agreed to help here :)

### PR DESCRIPTION
**Pull request by FRosner**
Fixes #73

### CODE REVIEW

File: src/main/scala/de/frosner/ddq/constraints/ForeignKeyConstraint.scala [hunk 1]
```diff
@@ -2,40 +2,79 @@ package de.frosner.ddq.constraints
...
-      val renamedRef = referenceTable.select(refColumns.zip(renamedRefColumns).map {
+      }: _*))
+      val maybeRenamedRef = maybeRenamedDf.map(_ => referenceTable.select(refColumns.zip(renamedRefColumns).map {
         case (original, renamed) => new Column(original).as(renamed)
-      }: _*)
+      }: _*))
 
       // check if left outer join yields some null values
-      val leftOuterJoin = renamedDf.distinct.join(renamedRef, renamedColumns.map {
+      val maybeLeftOuterJoin = maybeRenamedRef.map(renamedRef => maybeRenamedDf.get.distinct.join(renamedRef, renamedColumns.map {
```
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ForeignKeyConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305054514/issues/source?bid=3033737&fileBranchId=3196266#l34)

File: src/main/scala/de/frosner/ddq/constraints/ColumnColumnConstraint.scala [hunk 2]
```diff
@@ -2,17 +2,42 @@ package de.frosner.ddq.constraints
...
+
 case class ColumnColumnConstraint(constraintColumn: Column) extends Constraint {
 
   val fun = (df: DataFrame) => {
-    val succeedingRows = df.filter(constraintColumn).count
-    val count = df.count
-    val failingRows = count - succeedingRows
+    val maybeSucceedingRows = Try(df.filter(constraintColumn).count)
+    val maybeCount = maybeSucceedingRows.map(_ => df.count)
+    val maybeFailingRows = maybeCount.map(count => count - maybeSucceedingRows.get)
```
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ColumnColumnConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305054507/issues/source?bid=3033737&fileBranchId=3196266#l12)

File: src/main/scala/de/frosner/ddq/constraints/JoinableConstraint.scala [hunk 3]
```diff
@@ -2,37 +2,72 @@ package de.frosner.ddq.constraints
...
+    val maybeDistinctBefore = maybeRenamedDfDistinct.map(_.count)
+    val maybeJoin = maybeRenamedDfDistinct.map(_.join(maybeRenamedRef.get, renamedColumns.map{
       case (baseColumn, refColumn) => new Column(baseColumn) === new Column(refColumn)
-    }.reduce(_ && _))
-    val matchingRows = join.distinct.count
-    val matchedKeysPercentage = ((matchingRows.toDouble / distinctBefore) * 100).round
+    }.reduce(_ && _)))
+    val maybeMatchingRows = maybeJoin.map(_.distinct.count)
+    val maybeMatchedKeysPercentage = maybeMatchingRows.map(matchingRows =>
+        ((matchingRows.toDouble / maybeDistinctBefore.get) * 100).round)
```
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/JoinableConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305054517/issues/source?bid=3033737&fileBranchId=3196266#l35)

File: src/main/scala/de/frosner/ddq/constraints/JoinableConstraint.scala [hunk 4]
```diff
@@ -2,37 +2,72 @@ package de.frosner.ddq.constraints
...
 
     JoinableConstraintResult(
       constraint = this,
-      distinctBefore = distinctBefore,
-      matchingKeys = matchingRows,
-      status = if (matchingRows > 0) ConstraintSuccess else ConstraintFailure
+      data = maybeMatchingRows.toOption.map(matchingRows => JoinableConstraintResultData(
+          distinctBefore = maybeDistinctBefore.get,
```
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/JoinableConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305054517/issues/source?bid=3033737&fileBranchId=3196266#l40)

File: src/main/scala/de/frosner/ddq/constraints/ConditionalColumnConstraint.scala [hunk 5]
```diff
@@ -2,17 +2,42 @@ package de.frosner.ddq.constraints
...
+
 case class ConditionalColumnConstraint(statement: Column, implication: Column) extends Constraint {
 
   val fun = (df: DataFrame) => {
-    val succeedingRows = df.filter(!statement || implication).count
-    val count = df.count
-    val failingRows = count - succeedingRows
+    val maybeSucceedingRows = Try(df.filter(!statement || implication).count)
+    val maybeCount = maybeSucceedingRows.map(_ => df.count)
+    val maybeFailingRows = maybeCount.map(count => count - maybeSucceedingRows.get)
```
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ConditionalColumnConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305054508/issues/source?bid=3033737&fileBranchId=3196266#l12)

File: src/main/scala/de/frosner/ddq/constraints/ConstraintUtil.scala [hunk 6]
```diff
@@ -0,0 +1,13 @@
+package de.frosner.ddq.constraints
+
+import scala.util.Try
+
+object ConstraintUtil {
+
+  def tryToStatus[T](tryObject: Try[T], successCondition: T => Boolean): ConstraintStatus =
+    tryObject.map(
```
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ConstraintUtil.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305054512/issues/source?bid=3033737&fileBranchId=3196266#l8)

File: src/main/scala/de/frosner/ddq/constraints/TypeConversionConstraint.scala [hunk 7]
```diff
@@ -3,21 +3,49 @@ package de.frosner.ddq.constraints
...
 
   val fun = (df: DataFrame) => {
     val originalColumn = new Column(columnName)
     val castedColumnName = columnName + "_casted"
-    val casted = df.select(originalColumn, originalColumn.cast(convertedType).as(castedColumnName))
-    val failedCastsCount = casted.filter(new Column(castedColumnName).isNull && originalColumn.isNotNull).count
-    val originalType = df.schema.find(_.name == columnName).get.dataType
+    val maybeCasted = Try(df.select(originalColumn, originalColumn.cast(convertedType).as(castedColumnName)))
+    val maybeFailedCastsCount = maybeCasted.map(_.filter(new Column(castedColumnName).isNull && originalColumn.isNotNull).count)
+    val maybeOriginalType = maybeFailedCastsCount.map(_ => df.schema.find(_.name == columnName).get.dataType)
```
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/TypeConversionConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305054522/issues/source?bid=3033737&fileBranchId=3196266#l16)

File: src/main/scala/de/frosner/ddq/constraints/TypeConversionConstraint.scala [hunk 8]
```diff
@@ -3,21 +3,49 @@ package de.frosner.ddq.constraints
...
     TypeConversionConstraintResult(
-      this,
-      originalType,
-      failedCastsCount,
-      if (failedCastsCount == 0) ConstraintSuccess else ConstraintFailure
+      constraint = this,
+      data = maybeOriginalType.toOption.map(originalType => TypeConversionConstraintResultData(
+        originalType = originalType,
+        failedRows = maybeFailedCastsCount.get
```
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/TypeConversionConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305054522/issues/source?bid=3033737&fileBranchId=3196266#l21)

File: src/main/scala/de/frosner/ddq/constraints/ConditionalColumnConstraint.scala (hunk 5 above)
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ConditionalColumnConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305236329/issues/source?bid=3033737&fileBranchId=3196266#l12)

File: src/main/scala/de/frosner/ddq/constraints/TypeConversionConstraint.scala (hunk 7 above)
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/TypeConversionConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305236343/issues/source?bid=3033737&fileBranchId=3196266#l16)

File: src/main/scala/de/frosner/ddq/constraints/TypeConversionConstraint.scala (hunk 8 above)
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/TypeConversionConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305236343/issues/source?bid=3033737&fileBranchId=3196266#l21)

File: src/main/scala/de/frosner/ddq/constraints/ColumnColumnConstraint.scala (hunk 2 above)
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ColumnColumnConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305236328/issues/source?bid=3033737&fileBranchId=3196266#l12)

File: src/main/scala/de/frosner/ddq/constraints/ConstraintUtil.scala (hunk 6 above)
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ConstraintUtil.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305236333/issues/source?bid=3033737&fileBranchId=3196266#l8)

File: src/main/scala/de/frosner/ddq/constraints/ConditionalColumnConstraint.scala (hunk 5 above)
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ConditionalColumnConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305338223/issues/source?bid=3033737&fileBranchId=3196266#l12)

File: src/main/scala/de/frosner/ddq/constraints/ColumnColumnConstraint.scala (hunk 2 above)
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ColumnColumnConstraint.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305338222/issues/source?bid=3033737&fileBranchId=3196266#l12)

File: src/main/scala/de/frosner/ddq/constraints/ConstraintUtil.scala (hunk 6 above)
Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ConstraintUtil.scala]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305338227/issues/source?bid=3033737&fileBranchId=3196266#l8)

Comment (FRosner) [inline src/main/scala/de/frosner/ddq/constraints/ConstraintUtil.scala:8]: Codacy Issue found: [Usage of get on optional type.](https://www.codacy.com/app/frank_7/drunken-data-quality/file/2305635415/issues/source?bid=3033737&fileBranchId=3196266#l8)
